import test from 'node:test';
import assert from 'node:assert/strict';
import { ACADEMIC_YEAR, ASSESSMENT_DEFAULT, SUBJECTS_DEFAULT, availableAcademicYears } from '../src/data/constants.js';
import { createLearningObjective, listLearningObjectives, phaseForClass } from '../src/services/objectives.js';
import { copyAcademicYearData, createAcademicYear, setSemesterReferenceActive } from '../src/services/references.js';
import { getAssessmentSettings, getAssessmentSheet, saveAssessmentSettings } from '../src/services/assessment.js';
import { fillAllAssessmentScores } from '../src/services/assessment-bulk.js';
import { saveDailyAttendanceMode } from '../src/services/report.js';
import { saveAllAutomaticReports } from '../src/services/report-bulk.js';
import { createStudent, listStudents, previewStudentExcelImport, commitStudentImport, studentTemplateExcel } from '../src/services/students.js';
import { ACTIVITY_PREDICATES, cocurricularDescriptionsForClass, getStudentCocurricular, listExtracurriculars, pramukaDescriptionsForClass, pramukaPresetForClass, saveCocurricularBulk, saveExtracurricularBulk } from '../src/services/completeness.js';
import { ATTITUDE_DIMENSIONS, listStudentAttitudes, saveStudentAttitude } from '../src/services/attitudes.js';
import { moveSubjectToGroup } from '../src/services/mapping.js';
import { formatIndonesianPrintDate, savePrintSettings } from '../src/services/print-settings.js';
import { buildBackup } from '../src/services/backup.js';
import { createOwnerVerifier, getOwnerActivationStatus, verifyOwnerActivationKey, activateOwnerAdmin } from '../src/services/owner-activation.js';
import { getSubjectMapping, loadDb, saveSubjectMapping } from '../src/services/storage.js';
import { resolveRoute } from '../src/core/router.js';

/* Tahun pelajaran untuk menguji isolasi antar tahun. Dipilih otomatis dari tahun yang BELUM
   disediakan aplikasi, karena aplikasi kini selalu menyediakan tahun dasar, tahun berjalan, dan
   tahun berikutnya. Dengan dihitung begini, test tidak akan bentrok lagi di tahun-tahun mendatang. */
const TAHUN_LAIN=(()=>{const tersedia=new Set(availableAcademicYears());let mulai=Number(ACADEMIC_YEAR.slice(0,4))+9;while(tersedia.has(`${mulai}/${mulai+1}`))mulai+=1;return `${mulai}/${mulai+1}`;})();

function memoryStorage(){const values=new Map();return {getItem:key=>values.has(key)?values.get(key):null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key),clear:()=>values.clear()};}
function setup(){globalThis.localStorage=memoryStorage();globalThis.sessionStorage=memoryStorage();}
const ganjil=`Ganjil ${ACADEMIC_YEAR}`;const admin={role:'admin',classId:null,accountId:'admin',academicYear:ACADEMIC_YEAR,semester:ganjil};
function teacher(classId='2A',semester=ganjil,academicYear=ACADEMIC_YEAR){return {role:'teacher',classId,accountId:`teacher:${classId}`,academicYear,semester};}
function addStudent(session,id='s12'){return createStudent(session,{id,classId:session.classId,nis:`NIS-${id}`,nisn:`NISN-${id}`,name:`Siswa ${id}`,gender:'L',religion:'Islam',birthPlace:'Bekasi',birthDate:'2017-01-02',parentName:'Orang Tua',phone:'',address:'Bekasi',photo:''});}
function onlySubject(session,id='agama'){saveSubjectMapping(session,SUBJECTS_DEFAULT.map(subject=>({...subject,active:subject.id===id})));}

test('tahun lama tetap arsip dan Mapping, Bobot, KKTP, serta TP dapat disalin tanpa ditimpa',()=>{setup();const old=teacher();onlySubject(old);saveAssessmentSettings(old,'agama',{...ASSESSMENT_DEFAULT,kktp:78});createLearningObjective(old,'agama',{description:'Tujuan tahun lama.'});createAcademicYear(admin,TAHUN_LAIN);const counts=copyAcademicYearData(admin,{fromAcademicYear:ACADEMIC_YEAR,toAcademicYear:TAHUN_LAIN});const next=teacher('2A',`Ganjil ${TAHUN_LAIN}`,TAHUN_LAIN);assert.ok(counts.subjectMappings>0);assert.ok(counts.assessmentSettings>0);assert.ok(counts.learningObjectives>0);assert.equal(getAssessmentSettings(next,'agama').kktp,78);assert.equal(listLearningObjectives(next,'agama')[0].code,'TP-1');setSemesterReferenceActive(admin,ganjil,false);assert.equal(getSubjectMapping(old).find(item=>item.id==='agama').active,true);const again=copyAcademicYearData(admin,{fromAcademicYear:ACADEMIC_YEAR,toAcademicYear:TAHUN_LAIN});assert.ok(again.skipped>0);});

test('import Excel siswa melalui preview, validasi, lalu simpan dengan satu Nama Orang Tua',()=>{setup();const session=teacher();const cells=['1201','001201','Alya Excel','P','Islam','Bekasi, 4 Maret 2017','Ibu Alya','','Jl. Satria'].map(value=>`<Cell><Data ss:Type="String">${value}</Data></Cell>`).join('');const xml=studentTemplateExcel().replace('</Table>',`<Row>${cells}</Row></Table>`);const preview=previewStudentExcelImport(session,xml,{classId:'2A'});assert.equal(preview.validCount,1);assert.equal(listStudents(session).length,0);commitStudentImport(session,preview);assert.equal(listStudents(session)[0].parentName,'Ibu Alya');assert.equal(listStudents(session)[0].phone,'');});

test('Isi Semua Nilai mengisi lima komponen dan melewati Harian saat Absensi ON',()=>{setup();const session=teacher();onlySubject(session);const student=addStudent(session);let result=fillAllAssessmentScores(session,'agama',80);assert.equal(result.savedTypes.length,5);assert.equal(getAssessmentSheet(session,'agama','daily').rows[0].score,80);saveDailyAttendanceMode(session,'agama',true);result=fillAllAssessmentScores(session,'agama',82);assert.deepEqual(result.skippedTypes,['daily']);assert.equal(getAssessmentSheet(session,'agama','daily').rows[0].score,80);assert.equal(getAssessmentSheet(session,'agama','formative').rows.find(row=>row.studentId===student.id).score,82);});

test('fase TP otomatis A/B/C dan fase yang tidak sesuai ditolak',()=>{setup();assert.equal(phaseForClass('1A'),'A');assert.equal(phaseForClass('4D'),'B');assert.equal(phaseForClass('6C'),'C');const session=teacher('5A');onlySubject(session);assert.throws(()=>createLearningObjective(session,'agama',{code:'TP-X',description:'Uji fase.',phase:'A'}),/wajib Fase C/);assert.equal(createLearningObjective(session,'agama',{code:'TP-C',description:'Uji fase benar.'}).phase,'C');});

test('simpan otomatis semua mapel memproses nilai dan deskripsi sekaligus',()=>{setup();const session=teacher();onlySubject(session);addStudent(session);createLearningObjective(session,'agama',{code:'TP-1',description:'memahami konsep.'});createLearningObjective(session,'agama',{code:'TP-2',description:'menerapkan konsep.'});fillAllAssessmentScores(session,'agama',80);const result=saveAllAutomaticReports(session);assert.equal(result.subjectCount,1);assert.equal(result.scoreCount,1);assert.equal(result.descriptionCount,1);assert.equal(result.errors.length,0);});

test('bulk predikat ekstrakurikuler dan kokurikuler tersimpan untuk semua siswa',()=>{setup();const session=teacher('4A');const first=addStudent(session,'bulk-a');addStudent(session,'bulk-b');assert.equal(pramukaPresetForClass(session.classId),'Pramuka Penggalang');const extra=saveExtracurricularBulk(session,{predicate:'Sangat Baik',description:pramukaDescriptionsForClass(session.classId)[0]});assert.equal(extra.studentCount,2);assert.equal(extra.saved.length,2);assert.equal(listExtracurriculars(session,first.id)[0].predicate,'Sangat Baik');const coco=saveCocurricularBulk(session,{activity:'Projek Lingkungan',predicate:'Baik',description:cocurricularDescriptionsForClass(session.classId)[0]});assert.equal(coco.studentCount,2);assert.equal(coco.saved.length,2);assert.equal(getStudentCocurricular(session,first.id).predicate,'Baik');assert.deepEqual(ACTIVITY_PREDICATES,['Cukup','Baik','Sangat Baik']);});

test('dimensi sikap bersifat opsional dan hanya dimensi terpilih yang tersimpan',()=>{setup();const session=teacher();const student=addStudent(session);assert.equal(listStudentAttitudes(session,student.id).filter(item=>item.status!=='EMPTY').length,0);saveStudentAttitude(session,student.id,ATTITUDE_DIMENSIONS[0].id,{level:'Berkembang Sesuai Harapan'});const filled=listStudentAttitudes(session,student.id).filter(item=>item.status!=='EMPTY');assert.equal(filled.length,1);assert.equal(filled[0].status,'AUTO');assert.equal(filled[0].classId,'2A');});

test('Mapping dapat pindah A/B dengan nomor kelompok terpisah',()=>{const moved=moveSubjectToGroup(SUBJECTS_DEFAULT,'agama','B');assert.equal(moved.find(item=>item.id==='agama').group,'B');const jumlah=g=>SUBJECTS_DEFAULT.filter(item=>item.group===g).length;const urut=n=>Array.from({length:n},(_,i)=>i+1);assert.deepEqual(moved.filter(item=>item.group==='A').map(item=>item.order),urut(jumlah('A')-1));assert.deepEqual(moved.filter(item=>item.group==='B').map(item=>item.order),urut(jumlah('B')+1));});

test('tanggal cetak menggunakan format Indonesia dan tersimpan per scope Guru',()=>{setup();const session=teacher();const value=savePrintSettings(session,{principalName:'Kepala Sekolah',principalNip:'19800101',teacherName:'Guru Kelas',teacherNip:'19900101',city:'Bekasi',printDate:'2026-01-23'});assert.equal(value.printDateLabel,'Bekasi, 23 Januari 2026');assert.equal(formatIndonesianPrintDate('2026-08-09','Bekasi'),'Bekasi, 9 Agustus 2026');});

test('backup Guru mencakup sikap, kokurikuler, ekskul, dan print settings tanpa secret plaintext',()=>{setup();const session=teacher();const student=addStudent(session);saveStudentAttitude(session,student.id,ATTITUDE_DIMENSIONS[0].id,{level:'Sangat Berkembang'});saveCocurricularBulk(session,{activity:'Projek',predicate:'Baik',description:cocurricularDescriptionsForClass(session.classId)[0]});saveExtracurricularBulk(session,{predicate:'Baik',description:pramukaDescriptionsForClass(session.classId)[0]});savePrintSettings(session,{principalName:'Kepala',principalNip:'123',teacherName:'Guru',teacherNip:'456',city:'Bekasi',printDate:'2026-01-23'});const payload=buildBackup(session);assert.equal(Object.keys(payload.data.attitudeProfiles).length,1);assert.equal(Object.keys(payload.data.cocurricularScores).length,1);assert.equal(Object.keys(payload.data.extracurricularScores).length,1);assert.equal(Object.keys(payload.data.printSettings).length,1);assert.doesNotMatch(JSON.stringify(payload),/owner-key|owner pin|password\s*:/i);});

test('Owner Activation Key memverifikasi key valid, menolak key/PIN salah, Guru, dan tidak menyimpan secret',async()=>{setup();const key={version:1,keyId:'owner-test',secret:btoa(String.fromCharCode(...new Uint8Array(32).fill(7)))};const verifier=await createOwnerVerifier(key,'24681357',{saltBytes:new Uint8Array(20).fill(4),iterations:1000});assert.equal(await verifyOwnerActivationKey(key,'24681357',verifier),true);assert.equal(await verifyOwnerActivationKey(key,'00000000',verifier),false);await assert.rejects(()=>activateOwnerAdmin({ownerKeyText:JSON.stringify(key),pin:'24681357',newPassword:'AdminSecure2026',actorRole:'teacher'}),/Guru tidak diizinkan/);await assert.rejects(()=>activateOwnerAdmin({ownerKeyText:JSON.stringify(key),pin:'salah',newPassword:'AdminSecure2026'}),/tidak valid/);const stored=JSON.stringify(loadDb());assert.doesNotMatch(stored,/24681357|AdminSecure2026/);assert.equal(getOwnerActivationStatus().remainingAttempts,4);});

test('route aktivasi hanya terbuka sebelum aktif dan tidak dapat dibuka oleh Guru',()=>{setup();assert.equal(resolveRoute('activation',null),'activation');assert.equal(resolveRoute('activation',teacher()),'dashboard');});
