import { activateOwnerAdmin, getOwnerActivationStatus } from '../services/owner-activation.js';
import { el, escapeHtml } from '../ui/dom.js';
import { icon } from '../ui/icons.js';

export function renderOwnerActivation({onComplete,onBack}){
  let ownerKeyText='';const status=getOwnerActivationStatus();
  const root=el(`<main class="login-page"><section class="login-visual"><div class="brand"><div class="brand-mark">${icon('school',24)}</div><div><div class="brand-title">e-Rapor</div><div class="brand-sub">SDN Satria Jaya 01</div></div></div><div class="creator"><strong>AKTIVASI PEMILIK</strong><p>Owner Activation Key tidak ditanam di aplikasi dan tidak disimpan setelah verifikasi.</p></div></section><section class="login-panel"><form class="login-card"><h1>Aktivasi Admin Pemilik</h1><p>Impor file kunci rahasia, masukkan PIN pemilik, lalu buat password Admin pertama.</p><div class="field"><label>Owner Activation Key</label><input class="input" type="file" accept="application/json,.json" data-owner-key required/><small data-file-status>Belum ada file dipilih.</small></div><div class="field"><label>Owner PIN</label><input class="input" type="password" inputmode="numeric" autocomplete="off" data-pin required/></div><div class="field"><label>Password Admin Baru</label><input class="input" type="password" autocomplete="new-password" data-password required minlength="8"/></div><div class="field"><label>Ulangi Password Admin</label><input class="input" type="password" autocomplete="new-password" data-confirm required minlength="8"/></div><div class="source-banner warning-banner ${status.blocked?'':'hidden'}" data-rate>${status.blocked?`Aktivasi dikunci sementara sampai ${new Date(status.blockedUntil).toLocaleTimeString('id-ID')}.`:''}</div><div class="login-error hidden" data-error></div><button class="btn btn-primary" type="submit" style="width:100%">Verifikasi & Aktivasi</button><button class="btn btn-light" type="button" data-back style="width:100%;margin-top:8px">Kembali ke Login</button></form></section></main>`);
  root.querySelector('[data-owner-key]').onchange=async event=>{const file=event.target.files?.[0];ownerKeyText='';if(!file)return;try{ownerKeyText=await file.text();root.querySelector('[data-file-status]').textContent=file.name;}catch{root.querySelector('[data-file-status]').textContent='File tidak dapat dibaca.';}};
  root.querySelector('[data-back]').onclick=()=>onBack?.();root.querySelector('form').onsubmit=async event=>{event.preventDefault();const errorBox=root.querySelector('[data-error]');errorBox.classList.add('hidden');const password=root.querySelector('[data-password]').value;if(password!==root.querySelector('[data-confirm]').value){errorBox.textContent='Konfirmasi password Admin tidak sama.';errorBox.classList.remove('hidden');return;}if(!ownerKeyText){errorBox.textContent='Pilih file Owner Activation Key terlebih dahulu.';errorBox.classList.remove('hidden');return;}const button=root.querySelector('[type="submit"]');button.disabled=true;button.textContent='Memverifikasi…';try{const result=await activateOwnerAdmin({ownerKeyText,pin:root.querySelector('[data-pin]').value,newPassword:password});root.innerHTML=`<main class="login-page"><section class="login-panel" style="margin:auto"><div class="login-card"><h1>Aktivasi Berhasil</h1><p>Instalasi sudah ditandai aktif. File kunci dan PIN tidak disimpan oleh aplikasi.</p><div class="recovery-code">${escapeHtml(result.recoveryCode)}</div><p>Simpan kode recovery ini. Kode hanya ditampilkan satu kali.</p><button class="btn btn-primary" data-finish style="width:100%">Lanjut ke Login</button></div></section></main>`;root.querySelector('[data-finish]').onclick=()=>onComplete?.();}catch(error){errorBox.textContent=error.message;errorBox.classList.remove('hidden');const latest=getOwnerActivationStatus();const rate=root.querySelector('[data-rate]');if(latest.blocked){rate.textContent=`Aktivasi dikunci sementara sampai ${new Date(latest.blockedUntil).toLocaleTimeString('id-ID')}.`;rate.classList.remove('hidden');}}finally{if(button.isConnected){button.disabled=false;button.textContent='Verifikasi & Aktivasi';}}};return root;
}
