import { getAdminAssessmentStatus } from '../services/admin-status.js';
import { listReferenceAcademicYears, listReferenceSemesters } from '../services/references.js';
import { el, escapeHtml } from '../ui/dom.js';

function badge(complete){return complete?'<span class="badge badge-active">Lengkap</span>':'<span class="badge badge-inactive">Belum Lengkap</span>';}

export function renderAdminStatus(session){
  let academicYear=session.academicYear,semester=session.semester,selectedClassId='';const root=el(`<div><div class="page-head"><div><h1>Status Penilaian</h1><p>Monitoring nilai, deskripsi, dan kelengkapan rapor seluruh 24 rombel dari data tersimpan.</p></div></div><section class="card admin-status-filter" data-filter></section><div data-view></div><section class="card admin-status-detail hidden" data-detail></section></div>`);const filter=root.querySelector('[data-filter]'),view=root.querySelector('[data-view]'),detail=root.querySelector('[data-detail]');let current=null;
  function semesterOptions(year,selected){return listReferenceSemesters({academicYear:year}).map(item=>`<option value="${escapeHtml(item.label)}" ${item.label===selected?'selected':''}>${escapeHtml(item.name)}</option>`).join('');}
  function drawFilter(){const years=listReferenceAcademicYears();if(!years.some(item=>item.id===academicYear))academicYear=years[0]?.id||session.academicYear;const available=listReferenceSemesters({academicYear});if(!available.some(item=>item.label===semester))semester=available[0]?.label||session.semester;filter.innerHTML=`<div class="field"><label>Tahun Pelajaran</label><select class="input" data-year>${years.map(item=>`<option value="${escapeHtml(item.id)}" ${item.id===academicYear?'selected':''}>${escapeHtml(item.label)}</option>`).join('')}</select></div><div class="field"><label>Semester</label><select class="input" data-semester>${semesterOptions(academicYear,semester)}</select></div>`;filter.querySelector('[data-year]').onchange=event=>{academicYear=event.target.value;semester=listReferenceSemesters({academicYear})[0]?.label||'';selectedClassId='';draw();};filter.querySelector('[data-semester]').onchange=event=>{semester=event.target.value;selectedClassId='';draw();};}
  function drawDetail(){const data=current.classes.find(item=>item.classId===selectedClassId);if(!data){detail.classList.add('hidden');return;}detail.classList.remove('hidden');detail.innerHTML=`<div class="section-head"><div><h3>Detail Kelas ${escapeHtml(data.classId)}</h3><p>${data.studentCount} siswa · ${data.subjectCount} mapel aktif · ${escapeHtml(data.semester)}</p></div>${badge(data.status==='COMPLETE')}</div><div class="admin-subject-detail">${data.subjects.map(item=>`<article><div class="completion-head"><strong>${escapeHtml(item.subject.name)}</strong>${badge(item.status==='COMPLETE')}</div><div class="completion-numbers"><span><b>${item.scoreComplete}/${item.studentCount}</b>Nilai</span><span><b>${item.descriptionComplete}/${item.studentCount}</b>Deskripsi</span><span><b>${item.percentage}%</b>Progres</span></div>${item.missing.length?`<div class="admin-missing-list"><small>Siswa belum lengkap</small>${item.missing.map(row=>`<span><b>${escapeHtml(row.student.name)}</b>${[row.missingScore?'Nilai':'',row.missingDescription?'Deskripsi':''].filter(Boolean).join(' & ')}</span>`).join('')}</div>`:'<p class="complete-text">Nilai dan deskripsi seluruh siswa sudah lengkap.</p>'}</article>`).join('')}</div><div class="section-head admin-report-missing-head"><div><h3>Kelengkapan Rapor per Siswa</h3><p>Identitas, nilai, deskripsi, absensi, ekstrakurikuler, catatan, dan status akhir.</p></div><span class="badge badge-a">${data.reportIncompleteStudents} belum lengkap</span></div>${data.students.length?`<div class="admin-report-students">${data.students.map(row=>`<article><div><strong>${escapeHtml(row.student.name)}</strong><span>${escapeHtml(row.student.nis)} · ${row.percentage}%</span></div>${badge(row.status==='COMPLETE')}${row.missing.length?`<p>Kurang: ${escapeHtml(row.missing.join(', '))}</p>`:'<p class="complete-text">Semua komponen lengkap.</p>'}</article>`).join('')}</div>`:'<div class="empty-inline">Belum ada Data Siswa pada rombel dan periode ini.</div>'}`;detail.scrollIntoView({behavior:'smooth',block:'start'});}
  function draw(){drawFilter();current=getAdminAssessmentStatus(session,{academicYear,semester});view.innerHTML=`<div class="assessment-summary admin-status-summary"><article class="stat-card"><div class="stat-label">Rombel Lengkap</div><div class="stat-value">${current.completeClasses}</div><div class="stat-foot">dari ${current.classCount} rombel</div></article><article class="stat-card"><div class="stat-label">Jumlah Siswa</div><div class="stat-value">${current.totalStudents}</div><div class="stat-foot">scope aktif</div></article><article class="stat-card"><div class="stat-label">Progres Nilai</div><div class="stat-value">${current.scorePercentage}%</div><div class="bar"><span style="width:${current.scorePercentage}%"></span></div></article><article class="stat-card"><div class="stat-label">Progres Deskripsi</div><div class="stat-value">${current.descriptionPercentage}%</div><div class="bar"><span style="width:${current.descriptionPercentage}%"></span></div></article></div><div class="admin-class-status-grid">${current.classes.map(item=>`<button class="card admin-class-status ${item.classId===selectedClassId?'selected':''}" data-class="${escapeHtml(item.classId)}"><div class="completion-head"><strong>Kelas ${escapeHtml(item.classId)}</strong>${badge(item.status==='COMPLETE')}</div><div class="admin-class-count">${item.studentCount} siswa · ${item.subjectCount} mapel</div><div class="admin-progress-row"><span>Nilai</span><div class="bar"><i style="width:${item.scorePercentage}%"></i></div><b>${item.scorePercentage}%</b></div><div class="admin-progress-row"><span>Deskripsi</span><div class="bar"><i style="width:${item.descriptionPercentage}%"></i></div><b>${item.descriptionPercentage}%</b></div><div class="admin-progress-row"><span>Rapor</span><div class="bar"><i style="width:${item.reportPercentage}%"></i></div><b>${item.reportPercentage}%</b></div></button>`).join('')}</div>`;view.querySelectorAll('[data-class]').forEach(button=>button.onclick=()=>{selectedClassId=button.dataset.class;draw();});drawDetail();}
  draw();return root;
}
