import { ATTITUDE_DIMENSIONS, ATTITUDE_LEVELS, generateAttitudeDescription, listStudentAttitudes, saveClassAttitudeBulk, saveStudentAttitude } from '../services/attitudes.js';
import { listStudents } from '../services/students.js';
import { el, escapeHtml, toast } from '../ui/dom.js';
import { icon } from '../ui/icons.js';

export function renderAttitudes(session){
  const students=listStudents(session,{classId:session.classId});let studentId=students[0]?.id||'';
  const root=el(`<div><div class="page-head"><div><h1>Dimensi Nilai Sikap</h1><p>Profil Pelajar Pancasila · enam dimensi opsional, tersimpan per siswa dan scope aktif.</p></div><div class="actions"><button class="btn btn-light" data-apply-all>Isi Semua Siswa</button><button class="btn btn-primary" data-save>${icon('save',17)} Simpan Sikap</button></div></div><section class="card module-filter"><div class="field compact-field"><label>Siswa</label><select class="input" data-student>${students.map(student=>`<option value="${escapeHtml(student.id)}">${escapeHtml(student.name)} · ${escapeHtml(student.nis)}</option>`).join('')}</select></div><div class="scope-note">Kelas ${escapeHtml(session.classId)}<span>${escapeHtml(session.semester)} · ${escapeHtml(session.academicYear)}</span></div></section><div data-view></div></div>`);const view=root.querySelector('[data-view]');
  function draw(){if(!studentId){view.innerHTML='<section class="card empty-state"><h3>Belum ada Data Siswa</h3></section>';root.querySelector('[data-save]').disabled=true;root.querySelector('[data-apply-all]').disabled=true;return;}const records=listStudentAttitudes(session,studentId);view.innerHTML=`<section class="card"><div class="section-head"><div><h3>Dimensi Sikap</h3><p>Gunakan Generate lalu edit bila diperlukan. Dimensi boleh dibiarkan kosong.</p></div></div><div class="attitude-list">${records.map(record=>`<article data-dimension="${record.dimensionId}"><div><strong>${escapeHtml(record.dimensionLabel)}</strong><span class="badge ${record.status==='EMPTY'?'badge-inactive':'badge-active'}">${record.status==='AUTO'?'Otomatis':record.status==='EDITED'?'Diedit Guru':'Opsional'}</span></div><div class="form-grid"><div class="field"><label>Capaian</label><select class="input" data-level><option value="">Tidak diisi</option>${ATTITUDE_LEVELS.map(level=>`<option ${record.level===level?'selected':''}>${escapeHtml(level)}</option>`).join('')}</select></div><div class="field form-span-2"><label>Deskripsi</label><textarea class="input" rows="3" data-description>${escapeHtml(record.description)}</textarea></div></div><button class="btn btn-light btn-small" data-generate>Generate</button></article>`).join('')}</div></section>`;view.querySelectorAll('[data-dimension]').forEach(row=>{row.querySelector('[data-generate]').onclick=()=>{const level=row.querySelector('[data-level]').value;if(!level){toast('Pilih capaian terlebih dahulu.','warning');return;}const student=students.find(item=>item.id===studentId);row.querySelector('[data-description]').value=generateAttitudeDescription(student.name,row.dataset.dimension,level);};});}
  function openBulk(){const modal=el(`<div class="modal-backdrop"><form class="modal-card"><div class="modal-head"><div><h3>Isi Sikap Semua Siswa</h3><p>Deskripsi otomatis menyesuaikan nama setiap siswa.</p></div><button class="btn btn-light btn-icon" type="button" data-close>${icon('x',17)}</button></div><div class="field"><label>Dimensi yang diisi *</label><div class="objective-reference-list">${ATTITUDE_DIMENSIONS.map(item=>`<label class="objective-reference-item"><input type="checkbox" name="dimension" value="${escapeHtml(item.id)}"/><span>${escapeHtml(item.label)}</span></label>`).join('')}</div><div class="objective-reference-foot">Hanya dimensi yang dicentang yang akan diisi. Dimensi lain tetap kosong dan tidak muncul di rapor.</div></div><div class="field"><label>Capaian</label><select class="input" name="level">${ATTITUDE_LEVELS.map(level=>`<option>${escapeHtml(level)}</option>`).join('')}</select></div><div class="modal-actions"><button class="btn btn-light" type="button" data-cancel>Batal</button><button class="btn btn-primary" type="submit">Terapkan ke ${students.length} Siswa</button></div></form></div>`);document.body.append(modal);const close=()=>modal.remove();modal.querySelector('[data-close]').onclick=close;modal.querySelector('[data-cancel]').onclick=close;modal.querySelector('form').onsubmit=event=>{event.preventDefault();try{const form=event.currentTarget;const dipilih=[...form.querySelectorAll('input[name="dimension"]:checked')].map(item=>item.value);if(!dipilih.length){toast('Centang minimal satu dimensi sikap.','warning');return;}const saved=saveClassAttitudeBulk(session,dipilih,form.elements.level.value);close();draw();toast(`${dipilih.length} dimensi diterapkan ke ${students.length} siswa (${saved.length} catatan).`);}catch(error){toast(error.message,'error');}};}
  root.querySelector('[data-student]').onchange=event=>{studentId=event.target.value;draw();};root.querySelector('[data-apply-all]').onclick=openBulk;root.querySelector('[data-save]').onclick=()=>{let saved=0;try{view.querySelectorAll('[data-dimension]').forEach(row=>{const level=row.querySelector('[data-level]').value;if(!level)return;saveStudentAttitude(session,studentId,row.dataset.dimension,{level,description:row.querySelector('[data-description]').value});saved+=1;});draw();toast(`${saved} dimensi sikap berhasil disimpan.`);}catch(error){toast(error.message,'error');}};draw();return root;
}
