import { CLASSES } from '../data/constants.js';
import { dailyAttendanceRecap } from '../services/attendance.js';
import { getAdminAssessmentStatus } from '../services/admin-status.js';
import { getReportCompleteness } from '../services/documents.js';
import { getAdminProfile, getSchoolMaster, getTeacherProfile } from '../services/master.js';
import { getSubjectMapping } from '../services/storage.js';
import { listStudents } from '../services/students.js';
import { digitalGauge } from '../ui/digital-gauge.js';
import { icon } from '../ui/icons.js';
import { el, escapeHtml } from '../ui/dom.js';

function stat(label,value,iconName,foot=''){return `<article class="stat-card"><div class="stat-top"><div><div class="stat-label">${label}</div><div class="stat-value">${value}</div></div><div class="stat-icon">${icon(iconName,20)}</div></div>${foot?`<div class="stat-foot">${foot}</div>`:''}</article>`;}
function categoryProgress(report,key){return report.studentCount?Math.round(report.students.filter(row=>row.categories[key]!==false).length/report.studentCount*100):0;}

export function renderDashboard(session){
  const isAdmin=session.role==='admin';const school=getSchoolMaster();const profile=isAdmin?getAdminProfile():getTeacherProfile(session.classId);const activeSubjects=getSubjectMapping(session).filter(subject=>subject.active).length;const students=listStudents(session,{classId:isAdmin?'ALL':session.classId});const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);const daily=isAdmin?null:dailyAttendanceRecap(session,today,{classId:session.classId});const attendancePercentage=daily?.saved&&students.length?Math.round(daily.totals.Hadir/students.length*100):0;
  const adminStatus=isAdmin?getAdminAssessmentStatus(session):null;const report=isAdmin?null:getReportCompleteness(session);const reportPercentage=isAdmin?adminStatus.reportPercentage:report.overallPercentage;
  const stats=isAdmin?[stat('Jumlah Rombel',String(CLASSES.length),'school','Kelas 1A sampai 6D'),stat('Data Siswa',String(students.length),'users','Mengikuti semester aktif'),stat('Guru / Wali Kelas',String(CLASSES.length),'user','Satu wali kelas per rombel'),stat('Mata Pelajaran',String(activeSubjects),'file','Mengikuti mapping aktif')]:[stat('Rombel Aktif',session.classId,'school',session.semester),stat('Jumlah Siswa',String(students.length),'users',students.length?'Data siswa tersimpan':'Belum ada data siswa'),stat('Kehadiran Hari Ini',daily?.saved?`${attendancePercentage}%`:'—','calendar',daily?.saved?'Berdasarkan absensi tersimpan':'Belum ada absensi'),stat('Kelengkapan Rapor',`${reportPercentage}%`,'check-circle','Data kelengkapan tersimpan')];
  const progress=isAdmin?adminStatus.classes.slice(0,8).map(item=>({name:`Kelas ${item.classId}`,p:item.reportPercentage})):['scores','descriptions','attendance','extracurricular','homeroomNote',...(String(session.semester).startsWith('Genap ')?['finalStatus']:[])].map(key=>({name:{scores:'Nilai',descriptions:'Deskripsi',attendance:'Absensi',extracurricular:'Ekskul',homeroomNote:'Catatan',finalStatus:'Status Akhir'}[key],p:categoryProgress(report,key)}));
  const gauges=isAdmin?[digitalGauge(adminStatus.scorePercentage,{label:'Nilai',caption:'24 rombel'}),digitalGauge(adminStatus.descriptionPercentage,{label:'Deskripsi',tone:'blue',caption:'24 rombel'}),digitalGauge(adminStatus.reportPercentage,{label:'Kelengkapan',tone:'green',caption:'Seluruh kelas'})]:[digitalGauge(attendancePercentage,{label:'Hadir Hari Ini',tone:'blue',caption:daily?.saved?'Absensi tersimpan':'Belum tersimpan'}),digitalGauge(reportPercentage,{label:'Rapor Lengkap',tone:'green',caption:`Kelas ${session.classId}`})];
  return el(`<div><div class="page-head"><div><h1>Dashboard ${escapeHtml(profile.name)}</h1><p>${escapeHtml(school.name)} · ${escapeHtml(session.semester)}${isAdmin?'':` · Wali Kelas ${escapeHtml(session.classId)}`}</p></div></div><section class="grid stat-grid">${stats.join('')}</section><section class="card gauge-summary-card"><div><h3>Ringkasan Digital</h3><p class="muted">Dihitung dari data aktif yang sudah tersimpan.</p></div><div class="digital-gauge-grid">${gauges.join('')}</div></section><section class="grid dashboard-grid"><article class="card"><h3>${isAdmin?'Progress Pengisian Rapor':'Status Kelengkapan Kelas'}</h3><div class="progress-list">${progress.map(item=>`<div class="progress-row"><strong>${item.name}</strong><div class="bar"><span style="width:${item.p}%"></span></div><span>${item.p}%</span></div>`).join('')}</div></article><article class="card"><h3>Data Master Aktif</h3><div class="activity-list"><div class="activity-item"><strong>${escapeHtml(school.name)}</strong><div class="muted">Kepala Sekolah: ${escapeHtml(school.principalName||'Belum diisi')}</div></div><div class="activity-item"><strong>${escapeHtml(profile.name)}</strong><div class="muted">${isAdmin?'Administrator':`Wali Kelas ${session.classId}`} · NIP ${escapeHtml(profile.nip||'belum diisi')}</div></div><div class="activity-item"><strong>Backup & Restore</strong><div class="muted">Snapshot pemulihan tersedia di Pengaturan.</div></div></div></article></section></div>`);
}
