import { changeOwnPassword } from '../services/auth.js';
import { getAdminProfile, getSchoolMaster, getTeacherProfile, saveAdminProfile, saveTeacherProfile } from '../services/master.js';
import { el, escapeHtml, toast } from '../ui/dom.js';
import { icon } from '../ui/icons.js';

function initials(name){return String(name||'?').split(/\s+/).filter(Boolean).slice(0,2).map(word=>word[0]).join('').toUpperCase();}
function photo(profile,size='profile-master-photo'){return profile.photo?`<img class="${size}" src="${escapeHtml(profile.photo)}" alt="Foto ${escapeHtml(profile.name)}"/>`:`<div class="${size} student-initials">${escapeHtml(initials(profile.name))}</div>`;}

export function renderProfile(session){
  const school=getSchoolMaster();const root=el(`<div><div class="page-head"><div><h1>Profile</h1><p>Identitas pengguna dari Data Master lokal.</p></div><div class="actions"><button class="btn btn-primary" data-edit>${icon('edit',16)} Edit Profil</button><button class="btn btn-light" data-password>Ubah Password</button></div></div><div data-card></div></div>`);const card=root.querySelector('[data-card]');
  function current(){return session.role==='admin'?getAdminProfile():getTeacherProfile(session.classId);}
  function draw(){const profile=current();card.innerHTML=`<section class="card master-profile-card">${photo(profile)}<div><h2>${escapeHtml(profile.name)}</h2><p>${escapeHtml(school.name)}</p><div class="profile-master-grid"><span><b>Peran</b>${session.role==='admin'?'Administrator':`Guru / Wali Kelas ${session.classId}`}</span><span><b>NIP</b>${escapeHtml(profile.nip||'Belum diisi')}</span><span><b>No. HP</b>${escapeHtml(profile.phone||'Belum diisi')}</span><span><b>Email</b>${escapeHtml(profile.email||'Belum diisi')}</span>${session.role==='teacher'?`<span><b>Rombel</b>${escapeHtml(profile.classId)}</span>`:''}<span><b>Semester</b>${escapeHtml(session.semester)}</span></div></div></section>`;}
  function openEdit(){let profile=current(),photoData=profile.photo||'';const modal=el(`<div class="modal-backdrop"><form class="modal-card modal-wide"><div class="modal-head"><div><h3>Edit Profil ${session.role==='teacher'?`Guru ${escapeHtml(session.classId)}`:'Admin'}</h3><p>Perubahan otomatis digunakan Dashboard dan dokumen.</p></div><button type="button" class="btn btn-light btn-icon" data-close>${icon('x',17)}</button></div><div class="student-photo-field"><div data-photo-preview>${photo(profile,'student-photo student-photo-form')}</div><div><label class="btn btn-light" for="masterProfilePhoto">Pilih Foto</label><input class="hidden" id="masterProfilePhoto" type="file" accept="image/*" data-photo/><p class="muted">Maksimal 1 MB, disimpan lokal.</p></div></div><div class="form-grid"><div class="field form-span-2"><label>Nama</label><input class="input" name="name" value="${escapeHtml(profile.name)}" required/></div><div class="field"><label>NIP</label><input class="input" name="nip" value="${escapeHtml(profile.nip||'')}"/></div><div class="field"><label>No. HP</label><input class="input" name="phone" value="${escapeHtml(profile.phone||'')}"/></div><div class="field form-span-2"><label>Email</label><input class="input" type="email" name="email" value="${escapeHtml(profile.email||'')}"/></div>${session.role==='teacher'?`<div class="field"><label>Rombel</label><input class="input readonly" value="${escapeHtml(session.classId)}" readonly/></div>`:''}</div><div class="login-error hidden" data-error></div><div class="modal-actions"><button type="button" class="btn btn-light" data-cancel>Batal</button><button class="btn btn-primary" type="submit">Simpan Profil</button></div></form></div>`);document.body.append(modal);const form=modal.querySelector('form');const close=()=>modal.remove();modal.querySelector('[data-close]').onclick=close;modal.querySelector('[data-cancel]').onclick=close;modal.querySelector('[data-photo]').onchange=event=>{const file=event.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>1024*1024){toast('Foto harus berupa gambar maksimal 1 MB.','error');return;}const reader=new FileReader();reader.onload=()=>{photoData=String(reader.result);modal.querySelector('[data-photo-preview]').innerHTML=`<img class="student-photo student-photo-form" src="${escapeHtml(photoData)}" alt="Preview foto"/>`;};reader.readAsDataURL(file);};form.onsubmit=event=>{event.preventDefault();try{const input={name:form.elements.name.value,nip:form.elements.nip.value,phone:form.elements.phone.value,email:form.elements.email.value,photo:photoData};if(session.role==='admin')saveAdminProfile(session,input);else saveTeacherProfile(session,session.classId,input);close();draw();toast('Profil berhasil diperbarui.');}catch(error){const box=modal.querySelector('[data-error]');box.textContent=error.message;box.classList.remove('hidden');}};}
  function openPassword(){const modal=el(`<div class="modal-backdrop"><form class="modal-card"><div class="modal-head"><div><h3>Ubah Password</h3><p>Password baru akan disimpan sebagai salted hash.</p></div><button type="button" class="btn btn-light btn-icon" data-close>${icon('x',17)}</button></div><div class="field"><label>Password Saat Ini</label><input class="input" type="password" name="current" required/></div><div class="field"><label>Password Baru</label><input class="input" type="password" name="next" required/></div><div class="field"><label>Ulangi Password Baru</label><input class="input" type="password" name="confirm" required/></div><div class="login-error hidden" data-error></div><div class="modal-actions"><button type="button" class="btn btn-light" data-cancel>Batal</button><button class="btn btn-primary" type="submit">Ubah Password</button></div></form></div>`);document.body.append(modal);const form=modal.querySelector('form');const close=()=>modal.remove();modal.querySelector('[data-close]').onclick=close;modal.querySelector('[data-cancel]').onclick=close;form.onsubmit=async event=>{event.preventDefault();if(form.elements.next.value!==form.elements.confirm.value){const box=modal.querySelector('[data-error]');box.textContent='Konfirmasi password tidak sama.';box.classList.remove('hidden');return;}try{await changeOwnPassword(session,form.elements.current.value,form.elements.next.value);close();toast('Password berhasil diubah.');}catch(error){const box=modal.querySelector('[data-error]');box.textContent=error.message;box.classList.remove('hidden');}};}
  root.querySelector('[data-edit]').onclick=openEdit;root.querySelector('[data-password]').onclick=openPassword;draw();return root;
}
